theme: jekyll-theme-cayman
title: 💎 metaGEM
Description: An easy-to-use workflow for generating context specific genome-scale metabolic models and predicting metabolic interactions within microbial communities directly from metagenomic data.
