path:
    root: /home/zorrilla/workspace/tutorial
folder:
    data: dataset
    logs: logs
    assemblies: assemblies
    scripts: scripts
    concoctInput: concoct_input
    concoctOutput: concoct_output
    maxbin: maxbin_output
    metabat: metabat_output
    refined: refined_bins
    reassembled: reassembled_bins
    classification: classification
    abundance: abundance
    GRiD: GRiD
    GEMs: GEMs
    SMETANA: SMETANA
    memote: memote
scripts:
    kallisto2concoct: /home/zorrilla/workspace/tutorial/scripts/kallisto2concoct.py
    binFilter: /home/zorrilla/workspace/tutorial/scripts/binFilter.py
dbs:
    carveme: /home/zorrilla/workspace/tutorial/scripts/media_db.tsv
